name: Build

on:

  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgudev-1.0-dev libglibmm-2.68-dev
          version: build

      - name: Use ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true

      - name: Checkout
        uses: actions/checkout@v5

      - name: Bootstrap
        run: ./bootstrap

      - name: Configure
        run: ./configure --enable-examples

      - name: Build
        run: make

      - name: Check
        run: make check

      - name: Dist check
        run: make distcheck
