name: Build

on:

  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v5

      - name: Install dependencies
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgudev-1.0-dev libglibmm-2.68-dev

      - name: bootstrap
        run: ./bootstrap

      - name: configure
        run: ./configure --enable-examples

      - name: Build
        run: make

      - name: Check
        run: make check

      - name: Dist check
        run: make distcheck
